# TOKEN FOR BOT API
BOT_API_TOKEN = ""
# LINK ON CHANNEL OR ID CHANNEL
CHANNEL_ENTITY = "https://t.me/NEW_CHANNELTEST"
# SESSION STRING TOKEN BY USERBOT
SESSION_TOKEN = ""
# WORD FOR SET
MESSAGE_FOR_SET = "@good"
# WORD FOR REPLACE WITH NEW MESSAGE
MESSAGE_FOR_REMOVE = "@HUI"